server:
  port: 8888

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:\\\C:\Users\2507372\OneDrive - Cognizant\Desktop\LogiAll\LOGI-TRACK-MICRO-SERVICE\config-repo
management:
  endpoints:
    web:
      exposure:
        include: health,info